### ISSUE TITLE
DaggerAppComponent

### ISSUE THREAD

**Issue by Mfrenchy77** [ihorvitruk/buddysearch#3]
In module presentation, class App, your method intializeInjector()

You have appComponent = DaggerAppComponent

in the import statements it shows its supposed to be in the

    import com.buddysearch.android.presentation.di.component.DaggerAppComponent;
  
only see ActivityComponent and AppComponent

**Comment by ihorvitruk** [comment]
According to [Dagger 2 User Guide](https://google.github.io/dagger/users-guide):

> Dagger 2 is the first to **implement the full stack with generated code**. The guiding principle is to generate code that mimics the code that a user might have hand-written to ensure that dependency injection is as simple, traceable and performant as it can be.

It means, that if no compile errors or DI issues were found in your project, then your **DaggerAppComponent** will be generated automatically after you run (build) the project for the first time.
Let me know if you have some troubles with it.

**Comment by Mfrenchy77** [comment]
Thanks again!

**Comment by ihorvitruk** [comment]
You are welcome. Please let me know if you need some help.
Also, pay attention, that this repository also have **develop** branch that has newer updates than **master**. But in final case, develop will be merged into master as a new application **release**.

**Comment by Mfrenchy77** [comment]
Yeah, I was checking that out. I am using firebase create and sign in with email and password. I saw you were heading in that direction too.
