### ISSUE TITLE
Should I use this pattern?

### ISSUE THREAD

**Issue by carlosjs23** [ihorvitruk/buddysearch#4]
_This question will have more to do with the pattern than with this example of implementation._

I'm trying to understand the clean architecture, and getting in touch for the first time with RxJava and injection dependencies.

Considering that it'll take me even longer to understand all this, I'd like to know before starting to use this project as a base **if I could use this pattern for the development of my application**, all the functionality of the application (or most of it) will be Based on a map, and from certain conditions such as the user's position, one functionality or another will be available. Very similar to the way Google Maps works. My doubt arises more than anything because I consider that all the functionality of the map could be done in the same activity, and specific things like the entrance of users could be handled in other activities and I don't know if the clean architecture will complicate things more for me (I'm beginner) .

All this is for the sake of implementing an architecture that allows other developers to integrate into the future in the project and quickly.

regards

**Comment by ihorvitruk** [comment]
There is no single right way how to implement the code in your app.
Usage of Clean Architecture and MVP gives a lot of benefits. Read more about them [here](http://fernandocejas.com/2014/09/03/architecting-android-the-clean-way/) and [here](https://github.com/konmik/konmik.github.io/wiki/Introduction-to-Model-View-Presenter-on-Android).
I would always recommend to develop your app the same way, using Clean Architecture approach and MVC / MVP / MVVM
